'use client';

import React, { useState, useCallback } from 'react';
import { useAuth } from '@/lib/auth-context';
import { useRouter } from 'next/navigation';
import { memoryApi, ApiError } from '@/lib/api';
import { AppShell } from '@/components/layout/app-shell';
import { Icon, IconName } from '@/components/ui/icons';

interface MemoryResult {
  id: string;
  incident_id?: string;
  memory_type: string;
  content: string;
  similarity_score: number;
  metadata?: Record<string, any>;
  created_at?: string;
}

const MEMORY_TYPE_META: Record<string, { label: string; color: string; icon: IconName; description: string }> = {
  DECISION_RECORD: {
    label: 'Decision Record',
    color: 'border-amber-500/40 bg-amber-500/10 text-amber-300',
    icon: 'coordinator',
    description: 'AI-generated decisions with rationale and outcome tracking',
  },
  LESSON_LEARNED: {
    label: 'Lesson Learned',
    color: 'border-purple-500/40 bg-purple-500/10 text-purple-300',
    icon: 'reports',
    description: 'Validated post-incident insights for future operations',
  },
  ACTION_PLAN: {
    label: 'Action Plan',
    color: 'border-brand-500/40 bg-brand-500/10 text-brand-300',
    icon: 'deployment',
    description: 'Master incident task plans generated by the Coordinator Agent',
  },
  SPECIALIST_FINDINGS: {
    label: 'Specialist Findings',
    color: 'border-emerald-500/40 bg-emerald-500/10 text-emerald-300',
    icon: 'ai',
    description: 'Outputs from specialist AI agents (Weather, Medical, Shelter, etc.)',
  },
  SITUATION_REPORT: {
    label: 'Situation Report',
    color: 'border-cyan-500/40 bg-cyan-500/10 text-cyan-300',
    icon: 'audit',
    description: 'Time-stamped operational situation reports (SITREPs)',
  },
  WEATHER_OBSERVATION: {
    label: 'Weather Observation',
    color: 'border-sky-500/40 bg-sky-500/10 text-sky-300',
    icon: 'weather',
    description: 'Meteorological records tied to incident timelines',
  },
  FIELD_UPDATE: {
    label: 'Field Update',
    color: 'border-orange-500/40 bg-orange-500/10 text-orange-300',
    icon: 'satellite',
    description: 'Live field status updates from responders and automated systems',
  },
};

const SUGGESTED_QUERIES = [
  'shelter access road flooded Lagos',
  'hospital capacity exceeded flood',
  'convoy route blocked storm',
  'evacuation tidal surge coastal',
  'Agege Stadium capacity',
  'Ikeja Community Centre rejected',
];

function MemoryTypeBadge({ type }: { type: string }) {
  const meta = MEMORY_TYPE_META[type] ?? {
    label: type,
    color: 'border-slate-600 bg-slate-800 text-slate-300',
    icon: 'memory',
  };
  return (
    <span className={`inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs font-extrabold uppercase tracking-wider ${meta.color}`}>
      <Icon name={meta.icon} size={15} />
      {meta.label}
    </span>
  );
}

function SimilarityBar({ score }: { score: number }) {
  const pct = Math.round(score * 100);
  const color = pct >= 80 ? 'bg-emerald-400' : pct >= 60 ? 'bg-amber-400' : 'bg-slate-400';
  return (
    <div className="flex items-center gap-3">
      <span className="text-xs font-mono font-bold text-slate-300 w-10">{pct}%</span>
      <div className="w-24 h-2 rounded-full bg-slate-800">
        <div className={`h-2 rounded-full transition-all ${color}`} style={{ width: `${pct}%` }} />
      </div>
      <span className="text-xs text-slate-400 font-mono">similarity</span>
    </div>
  );
}

function MemoryCard({ result }: { result: MemoryResult }) {
  const [expanded, setExpanded] = useState(false);
  const isDecisionRecord = result.memory_type === 'DECISION_RECORD';

  return (
    <div className={`rounded-2xl border bg-slate-900/80 overflow-hidden transition-all ${
      isDecisionRecord ? 'border-amber-500/40 shadow-amber-500/10 shadow-xl' : 'border-slate-800'
    }`}>
      {isDecisionRecord && (
        <div className="bg-amber-500/15 border-b border-amber-500/30 px-6 py-2.5 flex items-center gap-2">
          <Icon name="coordinator" size={16} className="text-amber-400" />
          <span className="text-amber-300 text-xs font-extrabold tracking-wider uppercase">Decision Record — Memory Influenced Recommendation</span>
        </div>
      )}

      <div className="p-6 space-y-4">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <MemoryTypeBadge type={result.memory_type} />
          <SimilarityBar score={result.similarity_score} />
        </div>

        <p className={`text-base text-slate-100 font-normal leading-relaxed ${!expanded && 'line-clamp-4'}`}>
          {result.content}
        </p>

        {result.content.length > 200 && (
          <button
            onClick={() => setExpanded(e => !e)}
            className="text-sm text-[#9AF376] hover:underline font-bold inline-flex items-center gap-1"
          >
            {expanded ? '↑ Collapse' : '↓ Read full memory context'}
          </button>
        )}

        {result.metadata && Object.keys(result.metadata).length > 0 && (
          <div className="mt-4 pt-4 border-t border-slate-800 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2.5">
            {Object.entries(result.metadata)
              .filter(([k]) => !['vec', 'embedding'].includes(k))
              .slice(0, 6)
              .map(([k, v]) => (
                <div key={k} className="text-xs font-mono bg-slate-950 p-2 rounded-lg border border-slate-850">
                  <span className="text-slate-400 font-bold">{k}: </span>
                  <span className="text-slate-100">{String(v)}</span>
                </div>
              ))}
          </div>
        )}

        {result.created_at && (
          <p className="mt-3 text-xs font-mono text-slate-400">
            Stored: {new Date(result.created_at).toLocaleString()}
            {result.incident_id && ` · Incident ${result.incident_id.slice(0, 8)}…`}
          </p>
        )}
      </div>
    </div>
  );
}

export default function MemoryExplorerPage() {
  const { user, token, isLoading } = useAuth();
  const router = useRouter();
  const [query, setQuery] = useState('');
  const [results, setResults] = useState<MemoryResult[]>([]);
  const [isSearching, setIsSearching] = useState(false);
  const [hasSearched, setHasSearched] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [activeTypeFilter, setActiveTypeFilter] = useState<string | null>(null);

  const handleSearch = useCallback(async (searchQuery: string) => {
    if (!searchQuery.trim() || !token) return;
    setIsSearching(true);
    setError(null);
    setHasSearched(true);
    try {
      const result = await memoryApi.search(searchQuery, 15);
      setResults(result.data as MemoryResult[]);
    } catch (err) {
      if (err instanceof ApiError) setError(err.message);
      else setError('Vector search failed. Check API connection.');
      setResults([]);
    } finally {
      setIsSearching(false);
    }
  }, [token]);

  const onSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    handleSearch(query);
  };

  const filteredResults = activeTypeFilter
    ? results.filter(r => r.memory_type === activeTypeFilter)
    : results;

  const typeCounts = results.reduce<Record<string, number>>((acc, r) => {
    acc[r.memory_type] = (acc[r.memory_type] || 0) + 1;
    return acc;
  }, {});

  if (isLoading || !user) {
    return <div className="flex min-h-screen items-center justify-center text-slate-300 font-body text-base">Authenticating…</div>;
  }

  return (
    <AppShell
      title="Collective Memory Engine"
      subtitle="1024-dimensional semantic vector search over all disaster response histories"
    >
      <div className="max-w-5xl mx-auto space-y-8 font-body">

        {/* ── Search bar ───────────────────────────────────────────── */}
        <form onSubmit={onSubmit} className="relative">
          <div className="absolute inset-y-0 left-4 flex items-center pointer-events-none">
            <Icon name="search" size={22} className="text-slate-400" />
          </div>
          <input
            type="text"
            value={query}
            onChange={e => setQuery(e.target.value)}
            placeholder="Search: 'shelter access road flooded', 'hospital capacity Lagos flood'..."
            className="w-full rounded-2xl border border-slate-700 bg-slate-900 pl-14 pr-40 py-4 text-slate-100 placeholder-slate-400 focus:border-[#9AF376] focus:outline-none focus:ring-2 focus:ring-[#9AF376]/20 text-base transition-all font-medium"
          />
          <button
            type="submit"
            disabled={isSearching || !query.trim()}
            className="absolute right-2.5 top-2.5 bottom-2.5 rounded-xl bg-[#9AF376] px-6 text-sm font-extrabold text-slate-950 hover:brightness-110 disabled:opacity-40 transition-all flex items-center gap-2 shadow-[0_0_15px_rgba(154,243,118,0.2)]"
          >
            {isSearching ? (
              <><span className="h-4 w-4 border-2 border-slate-950/30 border-t-slate-950 rounded-full animate-spin" />Searching</>
            ) : (
              <>Vector Search</>
            )}
          </button>
        </form>

        {/* ── Suggested queries ────────────────────────────────────── */}
        {!hasSearched && (
          <div className="space-y-4">
            <p className="text-xs font-extrabold uppercase tracking-wider text-slate-300 font-mono">Suggested queries</p>
            <div className="flex flex-wrap gap-2.5">
              {SUGGESTED_QUERIES.map(q => (
                <button
                  key={q}
                  onClick={() => { setQuery(q); handleSearch(q); }}
                  className="rounded-full border border-slate-700 bg-slate-900 px-4 py-2 text-sm text-slate-200 hover:border-[#9AF376] hover:text-[#9AF376] font-medium transition-all"
                >
                  {q}
                </button>
              ))}
            </div>

            {/* ── Memory type legend with SVG Vector Icons ─────────────── */}
            <div className="rounded-2xl border border-slate-800 bg-slate-900/80 p-6 mt-6 space-y-4">
              <p className="text-xs font-extrabold uppercase tracking-wider text-slate-200 font-mono">
                Memory Types in this Platform
              </p>
              <div className="grid gap-4 sm:grid-cols-2">
                {Object.entries(MEMORY_TYPE_META).map(([type, meta]) => (
                  <div key={type} className="flex items-start gap-3.5 p-3.5 rounded-xl bg-slate-950 border border-slate-800">
                    <div className="p-2 rounded-lg bg-slate-900 text-[#9AF376] shrink-0 mt-0.5">
                      <Icon name={meta.icon} size={20} />
                    </div>
                    <div>
                      <span className={`inline-flex items-center gap-1.5 text-xs font-extrabold uppercase tracking-wider rounded-full border px-3 py-0.5 ${meta.color}`}>
                        {meta.label}
                      </span>
                      <p className="text-sm text-slate-200 font-normal mt-2 leading-relaxed">{meta.description}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* ── Error ───────────────────────────────────────────────── */}
        {error && (
          <div className="rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-base text-red-400 font-medium">{error}</div>
        )}

        {/* ── Results ─────────────────────────────────────────────── */}
        {hasSearched && !isSearching && (
          <div className="space-y-6">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <p className="text-sm font-bold text-slate-200">
                {filteredResults.length} vector match{filteredResults.length !== 1 ? 'es' : ''} found
              </p>
              {/* Type filter chips */}
              {Object.keys(typeCounts).length > 1 && (
                <div className="flex flex-wrap gap-2">
                  <button
                    onClick={() => setActiveTypeFilter(null)}
                    className={`rounded-full border px-3 py-1 text-xs font-bold transition-all ${
                      !activeTypeFilter ? 'border-[#9AF376] bg-[#9AF376]/20 text-[#9AF376]' : 'border-slate-700 text-slate-400 hover:border-slate-600'
                    }`}
                  >
                    All ({results.length})
                  </button>
                  {Object.entries(typeCounts).map(([type, count]) => {
                    const meta = MEMORY_TYPE_META[type];
                    return (
                      <button
                        key={type}
                        onClick={() => setActiveTypeFilter(type === activeTypeFilter ? null : type)}
                        className={`rounded-full border px-3 py-1 text-xs font-bold transition-all ${
                          activeTypeFilter === type ? meta?.color ?? 'border-slate-500 text-slate-200' : 'border-slate-700 text-slate-400 hover:border-slate-600'
                        }`}
                      >
                        {meta?.label || type} ({count})
                      </button>
                    );
                  })}
                </div>
              )}
            </div>

            {filteredResults.length === 0 ? (
              <div className="rounded-2xl border border-slate-800 bg-slate-900/40 p-12 text-center text-slate-400 text-base">
                No matching memories for &quot;{query}&quot;
              </div>
            ) : (
              <div className="space-y-5">
                {filteredResults.map(r => <MemoryCard key={r.id} result={r} />)}
              </div>
            )}
          </div>
        )}
      </div>
    </AppShell>
  );
}
